name: Terraform CI/CD

on:
  pull_request:
    branches:
      - dev
      - prod

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: env/${{ github.event.pull_request.base.ref }}

      - name: Terraform Plan
        run: terraform plan -no-color > plan.txt
        working-directory: env/${{ github.event.pull_request.base.ref }}

      - name: Post Plan to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: env/${{ github.event.pull_request.base.ref }}/plan.txt
