name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - prod

jobs:
  terraform:
    name: Terraform Pipeline
    runs-on: ubuntu-latest

    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Initialize Terraform
        run: terraform init
        working-directory: env/${{ github.ref_name }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: env/${{ github.ref_name }}

      - name: Terraform Apply (Dev Only)
        if: github.ref_name == 'dev'
        run: terraform apply -auto-approve
        working-directory: env/dev

      - name: Terraform Apply (Prod with Approval)
        if: github.ref_name == 'prod'
        uses: hmarr/auto-approve-action@v2 # Optional manual approval
      - run: terraform apply -auto-approve
        working-directory: env/prod
