name: Terraform CI/CD

on:
  push:
    branches:
      -  main  # Runs when changes are pushed to any branch starting with "feature/"
  
  pull_request:
    branches:
      - main  # Runs when a PR is created or updated for merging into the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
         

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init  # Initializes Terraform with the remote backend
      env: 
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      

    - name: Terraform Plan
      run: terraform plan  # Runs Terraform plan to preview changes (for feature branch push and PR creation)
      env: 
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Apply (on PR merge to main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Only runs on push to main (after merge)
      run: terraform apply -auto-approve  # Apply the changes
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}